module.exports = [
  { path: 'intro', title: 'Introduction' },
  { path: 'baseUrl', title: 'Base Url' },
  { path: 'authentication', title: 'Authentication' },
  { path: 'headers', title: 'HTTP Headers' },
  { path: 'errors', title: 'Errors' },
  { path: 'terminology', title: 'Terminology' },
  { path: 'attributeDefinitionSyntax', title: 'Attriubute Definitions' },
  { path: 'metav1', title: '~/meta.v1' },
  { path: 'bulk', title: '~/api/asset' },
  { path: 'queryv1', title: '~/query.v1' },
  { path: 'restv1Data', title: '~/rest-1.v1' },
  { path: 'activityStream', title: '~/api/activityStream' },
  { path: 'tags', title: '~/api/tags' },
  { path: 'loc', title: '~/loc-2.v1' },
]
